{{- if .Values.app }}
---
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: app-svc
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - name: app-port
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: renomy-app
